package helpers;

import com.github.javafaker.Faker;

/**
 * FakeUserData class provides constants FULL_NAME, PHONE_NUMBER, EMAIL, CITY, USERNAME, PASSWORD, COUNTRY.
 * These constants generated by methods which use library Faker.
 * <a href="https://github.com/DiUS/java-faker">DiUS/java-faker</a>
 */
public class FakeData {

    /**
     * Initialize Faker class instance.
     */
    static Faker faker = new Faker();

    /**
     * This method provides a full name, generated by Faker library.
     */
    public static String generateFullName() {
        return faker.name().fullName();
    }

    /**
     * This method provides a phone number, generated by Faker Library.
     */
    public static String generatePhoneNumber() {
        return faker.phoneNumber().phoneNumber();
    }

    /**
     * This method provides an email, generated by Faker Library.
     */
    public static String generateEmail() {
        return faker.internet().emailAddress();
    }

    /**
     * This method provides a city, generated by Faker Library.
     */
    public static String generateCity() {
        return faker.country().capital();
    }

    /**
     * This method provides a username, generated by Faker Library.
     */
    public static String generateUserName() {
        return faker.funnyName().name();
    }

    /**
     * This method provides a password, generated by Faker Library.
     */
    public static String generatePassword() {
        return faker.internet().password();
    }

    /**
     * This method provides a country, generated by Faker Library.
     */
    public static String generateCountry() {
        return faker.country().name();
    }
}
