package helpers;

import com.github.javafaker.Faker;

/**
 * FakeUserData class provides constants FULL_NAME, PHONE_NUMBER, EMAIL, CITY, USERNAME, PASSWORD, COUNTRY.
 * These constants generated by methods which use library Faker.
 * <a href="https://github.com/DiUS/java-faker">DiUS/java-faker</a>
 */
public class FakeData {

    /**
     * Initialize Faker class instance.
     */
    static Faker faker = new Faker();

    /**
     * The FULL_NAME constant contains a full name, collected from the getFullName() method.
     */
    public static final String FULL_NAME = getFullName();

    /**
     * The PHONE_NUMBER constant contains a phone number, collected from the getPhoneNumber() method.
     */
    public static final String PHONE_NUMBER = getPhoneNumber();

    /**
     * The EMAIL constant contains an email, collected from the getEmail() method.
     */
    public static final String EMAIL = getEmail();

    /**
     * The CITY constant contains a city, collected from the getCity() method.
     */
    public static final String CITY = getCity();

    /**
     * The USERNAME constant contains a username, collected from the getUserName() method.
     */
    public static final String USERNAME = getUserName();

    /**
     * The PASSWORD constant contains a password, collected from the getPassword() method.
     */
    public static final String PASSWORD = getPassword();

    /**
     * The COUNTRY constant contains a country, collected from the getCountry() method.
     */
    public static final String COUNTRY = getCountry();

    /**
     * This method provides a full name, generated by Faker library.
     */
    public static String getFullName() {
        return faker.name().fullName();
    }

    /**
     * This method provides a phone number, generated by Faker Library.
     */
    public static String getPhoneNumber() {
        return faker.phoneNumber().phoneNumber();
    }

    /**
     * This method provides an email, generated by Faker Library.
     */
    public static String getEmail() {
        return faker.internet().emailAddress();
    }

    /**
     * This method provides a city, generated by Faker Library.
     */
    public static String getCity() {
        return faker.country().capital();
    }

    /**
     * This method provides a username, generated by Faker Library.
     */
    public static String getUserName() {
        return faker.funnyName().name();
    }

    /**
     * This method provides a password, generated by Faker Library.
     */
    public static String getPassword() {
        return faker.internet().password();
    }

    /**
     * This method provides a country, generated by Faker Library.
     */
    public static String getCountry() {
        return faker.country().name();
    }
}
